spring:
  datasource:
    username: order_manager_owner
    password: order_manager_owner_pass
    url: jdbc:postgresql://localhost:5432/ordermanagerdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
